[templates.krypton]
input_path = "colors.json"
output_path = "~/.krypton/colors.json"

[templates.vicinae]
input_path = './templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'

[templates.vscode-raw]
input_path = './templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = './templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'

[templates.firefox-website-colors]
input_path = "./templates/firefox-colors.css"
output_path = "/home/arya/.config/mozilla/firefox/9zjtgk7n.default-release/chrome/colors.css"

[templates.spotify]
input_path = './templates/spicetify.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'
post_hook = 'spicetify apply'

[templates.zathura]
input_path = './templates/zathura-colors'
output_path = '~/.config/zathura/zathurarc'

[templates.pywalfox]
input_path = './templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
post_hook = './post-hook-scripts/gtk-themes-reload.sh'

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
